title: Todd Taomae
description: Blog and professional portfolio of Todd Taomae.

author: Todd Taomae
email: ttaomae@gmail.com
github_username: ttaomae
linkedin_username: ttaomae

# Build settings
markdown: kramdown
theme: minima

permalink: posts/:year/:month/:day/:slug.html

# jekyll-compress-html settings
compress_html:
  clippings: all
  blanklines: true

exclude:
  - Gemfile
  - Gemfile.lock
