title: Todd Taomae
description: Blog and professional portfolio of Todd Taomae.

google_analytics: UA-90444149-1

author: Todd Taomae
email: ttaomae@gmail.com
github_username: ttaomae
linkedin_username: ttaomae

# Build settings
markdown: kramdown
theme: minima

kramdown:
  auto_ids: false

permalink: posts/:year/:month/:slug

collections:
  projects:
    output: true
  my_categories:
    output: true
    permalink: posts/category/:slug
  my_tags:
    output: true
    permalink: posts/tag/:slug

# jekyll-compress-html settings
compress_html:
  clippings: all
  blanklines: true

gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE-CONTENT.md
  - LICENSE-SOURCE.md
